('Aidi', 'Aidi'),
('Akbash dog', 'Akbaş çoban köpegi'),
('Akita amerykańska', 'American akita'),
('Alpejski gończy krótkonożny, alpejski jamnikogończy', 'Alpenländische Dachsbracke'),
('Amerykański pitbulterier, amerykański pit bull terrier', 'American pit bull terrier'),
('Amerykański spaniel dowodny', 'American water spaniel'),
('Amerykański staffordshire terier, amerykański staffordshire terrier', 'American staffordshire terrier'),
('Amerykański staghound', 'American staghound'),
('Amerykański toy terier', 'American toy terrier'),
('Anatolian, anatolijski pies pasterski, anatolian karabash, owczarek anatolijski', 'Anadolu çoban köpegi'),
('Appenzeller', 'Appenzeller Sennenhund'),
('Australijski pies pasterski', 'Australian cattle dog'),
('Australijski silky terier', 'Australian silky terrier'),
('Basset artezyjsko-normandzki', 'Basset artésien normand'),
('Basset bretoński', 'Basset fauve de Bretagne'),
('Basset gaskoński', 'Basset bleu de Gascogne'),
('Basset', 'Basset hound'),
('Bedlington terier', 'Bedlington terrier'),
('Bernardyn, bernard, pies świętego Bernarda', 'Bernhardiner'),
('Berneński pies pasterski', 'Berner Sennenhund'),
('Biały owczarek szwajcarski', 'Berger blanc suisse'),
('Bokser', 'Deutscher Boxer'),
('Bolończyk', 'Bolognese'),
('Boston terier', 'Boston terrier'),
('Bouvier ardeński', 'Bouvier des Ardennes'),
('Brabantczyk', 'Petit brabançon'),
('Buhund norweski', 'Norsk buhund'),
('Buldog amerykański', 'American bulldog'),
('Buldog angielski', 'Bulldog'),
('Buldog francuski', 'Bouledogue français'),
('Bullenbeisser', 'Bullenbeißer (rasa wymarła)'),
('Bulmastif', 'Bullmastiff'),
('Bulterier miniaturowy', 'Miniature bull terrier'),
('Bulterier', 'Bull terrier'),
('Charcik włoski', 'Piccolo levriero italiano'),
('Chart afgański', 'Afghan hound'),
('Chart afrykański', 'Azawakh'),
('Chart arabski, chart z Maghrebu, arabski greyhound', 'Sloughi'),
('Chart hiszpański', 'Galgo espanol'),
('Chart kirgiski, tajgan kirgiski', 'Tajgan'),
('Chart perski', 'Saluki'),
('Chart polski', 'Chart polski'),
('Chart rosyjski, borzoj', 'Russkaja psowaja borzaja'),
('Chart szkocki', 'Deerhound'),
('Chart węgierski', 'Magyar agár'),
('Chart środkowoazjatycki', 'Tazy'),
('Chin japoński, czin japoński', 'Chin'),
('Chortaj', 'Chortaja borzaja'),
('Cocker spaniel amerykański', 'American cocker spaniel'),
('Cocker spaniel angielski', 'English cocker spaniel'),
('Collie długowłosy, owczarek szkocki długowłosy', 'Collie rough'),
('Collie krótkowłosy, owczarek szkocki krótkowłosy', 'Collie smooth'),
('Czarnogórski gończy górski', 'Crnogorski planinski gonič'),
('Czarny terier rosyjski', 'Czornyj tierjer'),
('Czuwacz słowacki, pies pasterski słowacki', 'Slovenský čuvač'),
('Dalmatyńczyk', 'Dalmatinski pas'),
('Dandie Dinmont terier', 'Dandie dinmont terrier'),
('Doberman', 'Dobermann'),
('Dog argentyński', 'Dogo argentino'),
('Dog kanaryjski, pies kanaryjski', 'Dogo canário'),
('Dog niemiecki', 'Deutsche Dogge'),
('Dog z Bordeaux, dog de Bordeaux', 'Dogue de Bordeaux'),
('Dog z Majorki, pies z Majorki', 'Perro dogo mallorquín'),
('Duńsko-szwedzki pies wiejski', 'Dansk-svensk gardshund'),
('Duży gończy anglo-francuski biało-czarny', 'Grand anglo-français blanc et noir'),
('Duży gończy anglo-francuski biało-pomarańczowy', 'Grand anglo-français blanc et orange'),
('Duży gończy anglo-francuski trójkolorowy', 'Grand anglo-français tricolore'),
('Duży gończy gaskoński', 'Grand bleu de Gascogne'),
('Duży münsterländer, duży munsterlander', 'Grosser Münsterländer'),
('Duży szwajcarski pies pasterski', 'Grosser schweizer Sennenhund'),
('Elkhund czarny', 'Norsk elghund sort'),
('Elkhund szary', 'Norsk elghund gra'),
('Fiński lapphund', 'Suomenlapinkoira'),
('Foksterier krótkowłosy', 'Fox terrier (smooth)'),
('Foksterier szorstkowłosy, foksterier gładkowłosy', 'Fox terrier (wire)'),
('Fousek', 'Czeski fousek'),
('Foxhound amerykański', 'American foxhound'),
('Foxhound angielski', 'English foxhound'),
('Fryzyjski pies dowodny', 'Wetterhoun'),
('Gończy Hamiltona', 'Hamiltonstover'),
('Gończy Schillera', 'Schillerstövare'),
('Gończy austriacki', 'Brandlbracke'),
('Gończy bośniacki szorstkowłosy, barak', 'Bosanski oštrodlaki gonič, barak'),
('Gończy chorwacki', 'Posavski gonič'),
('Gończy fiński', 'Suomenajokoira'),
('Gończy francuski biało-czarny', 'Français blanc et noir'),
('Gończy francuski biało-pomarańczowy', 'Français blanc et orange'),
('Gończy francuski trójkolorowy', 'Français tricolore'),
('Gończy grecki', 'Hellinikos ichnilatis'),
('Gończy hiszpański', 'Sabueso espanol'),
('Gończy istryjski krótkowłosy', 'Istarski kratkodlaki gonič'),
('Gończy istryjski szorstkowłosy', 'Istarski oštrodlaki gonič'),
('Gończy niemiecki', 'Deutsche Bracke'),
('Gończy polski', 'Gończy polski'),
('Gończy serbski trójkolorowy', 'Srpski trobojni gonič'),
('Gończy serbski, gończy bałkański', 'Srpski gonic'),
('Gończy smalandzki', 'Smalandsstövare'),
('Gończy styryjski', 'Steirische Rauhhaarbracke'),
('Gończy szwajcarski', 'Schweizer Laufhund'),
('Gończy słowacki, słowacki kopov', 'Slovenský kopov'),
('Gończy tyrolski', 'Tiroler Bracke'),
('Gończy węgierski', 'Erdélyi kopó'),
('Gończy włoski krótkowłosy', 'Segugio italiano a pelo raso'),
('Gończy włoski szorstkowłosy', 'Segugio italiano a pelo forte'),
('Gryfon Korthalsa', 'Griffon d’arret a poil dur Korthals'),
('Gryfonik belgijski', 'Griffon belge'),
('Gryfonik brukselski', 'Griffon bruxellois'),
('Grzywacz chiński', 'Chinese crested dog'),
('Hawańczyk', 'Bichon havanais'),
('Hiszpański pies dowodny, hiszpański pies wodny', 'Perro de agua espanol'),
('Hovawart', 'Hovawart'),
('Husky syberyjski', 'Siberian husky'),
('Irlandzki spaniel dowodny, spaniel wodny irlandzki', 'Irish water spaniel'),
('Islandzki szpic pasterski', 'Íslenskur fjárhundur'),
('Jamnik', 'Dackel'),
('Jindo', 'Jindo-kae'),
('Karelski pies na niedźwiedzie', 'Karjalankarhukoira'),
('Komondor', 'Komondor'),
('Kuwasz, kuvasz węgierski', 'Kuvasz'),
('Landseer', 'Landseer'),
('Leonberger', 'Leonberger'),
('Lwi piesek', 'Petit chien lion'),
('Łajka jakucka', 'Jakutskaja łajka'),
('Łajka karelo-fińska', 'Karelo-finskaja łajka'),
('Łajka rosyjsko-europejska', 'Russko-jewropiejskaja łajka'),
('Łajka wschodniosyberyjska', 'Wostocznosibirskaja łajka'),
('Łajka zachodniosyberyjska', 'Zapadnosibirskaja łajka'),
('Maltańczyk', 'Maltese'),
('Mastif angielski', 'Mastiff'),
('Mastif hiszpański', 'Mastín espanol'),
('Mastif neapolitański', 'Mastino napoletano'),
('Mastif pirenejski', 'Mastín del Pirineo'),
('Mastif tybetański', 'Do-khyi'),
('Mały gończy anglo-francuski', 'Anglo-français de petite vénerie'),
('Mały gończy gaskoński', 'Petit bleu de Gascogne'),
('Mały münsterländer, wyżeł mały, mały munsterlander', 'Kleiner Münsterländer'),
('Mops', 'Pug'),
('Moskiewski stróżujący', 'Moskowskaja storożewaja'),
('Nagi pies meksykański', 'Xoloitzquintle'),
('Nagi pies peruwiański', 'Perro sin pelo del Perú'),
('Niebieski spaniel pikardyjski', 'Épagneul bleu de Picardie'),
('Niemiecki terier myśliwski', 'Deutscher Jagdterrier'),
('Nowofundland', 'Newfoundland'),
('Ogar polski', 'Ogar polski'),
('Owczarek australijski (typ amerykański), owczarek australijski', 'Australian shepherd'),
('Owczarek australijski – kelpie, kelpie, australijski kelpie', 'Australian kelpie'),
('Owczarek belgijski', 'Chien de berger belge'),
('Owczarek chorwacki', 'Hrvatski ovčar'),
('Owczarek francuski beauceron, beauceron', 'Berger de Beauce, beauceron'),
('Owczarek francuski briard, briard, owczarek z Brie', 'Berger de Brie, briard'),
('Owczarek holenderski', 'Hollandse herdershond'),
('Owczarek kataloński', 'Gos d''atura catala'),
('Owczarek kaukaski', 'Kawkazskaja owczarka'),
('Owczarek kraski', 'Kraški ovčar'),
('Owczarek niemiecki', 'Deutscher Schäferhund'),
('Owczarek pikardyjski', 'Berger picard'),
('Owczarek pirenejski (a face rase, odmiana face rase)', 'Chien de berger des Pyrénées (face rase)'),
('Owczarek pirenejski (a poil long, odmiana face normal)', 'Chien de berger des Pyrénées (poil long)'),
('Owczarek podhalański', 'Polski owczarek podhalański'),
('Owczarek portugalski', 'Cao da Serra de Aires'),
('Owczarek południoworosyjski, jużak', 'Jużnorusskaja owczarka'),
('Owczarek rumuński karpatin', 'Ciobănesc românesc carpatin'),
('Owczarek rumuński mioritic', 'Ciobănesc românesc mioritic'),
('Owczarek staroangielski, bobtail', 'Old english sheepdog'),
('Owczarek szetlandzki', 'Shetland sheepdog'),
('Owczarek z Bergamo, bergamasco', 'Cane da pastore bergamasco'),
('Owczarek z Majorki', 'Ca de bestiar'),
('Owczarek środkowoazjatycki', 'Sriednieaziatskaja owczarka'),
('Pekińczyk, pekiński pies pałacowy', 'Pekingese'),
('Pies faraona', 'Pharaoh hound'),
('Pies grenlandzki', 'Gronlandshund'),
('Pies górski z Estrela', 'Cao da Serra da Estrela'),
('Pies laboratoryjny Horáka', 'Horákův laboratorní pes'),
('Pies z Canaan', 'Canaan dog'),
('Pies z Castro Laboreiro', 'Căo de Castro Laboreiro'),
('Pies z Maremmy i Arbuzzów, owczarek maremma', 'Cane da pastore maremmano-abruzzese'),
('Pies świętego Huberta', 'Chien de Saint-Hubert, bloodhound'),
('Pinczer austriacki', 'Österreichischer Pinscher'),
('Pinczer małpi, affenpinczer', 'Affenpinscher'),
('Pinczer miniaturowy, ratler, ratlerek', 'Zwergpinscher'),
('Pinczer średni, niemiecki pinczer średni, pinczer niemiecki', 'Deutscher Pinscher'),
('Pirenejski pies górski, duży pies pirenejski', 'Chien de montagne des Pyrénées'),
('Podenco kanaryjski', 'Podenco canario'),
('Podenco z Ibizy', 'Podenco ibicenco'),
('Podengo portugalski', 'Podengo portuguęs'),
('Pointer, pointer angielski', 'English pointer'),
('Polski owczarek nizinny', 'Polski owczarek nizinny'),
('Portugalski pies dowodny, portugalski pies wodny', 'Cao de água portugues'),
('Portugalski pies stróżujący', 'Rafeiro do Alentejo'),
('Posokowiec bawarski', 'Bayerischer Gebirgsschweißhund'),
('Posokowiec hanowerski', 'Hannoverscher Schweißhund'),
('Pudel', 'Caniche'),
('Pudelpointer', 'Pudelpointer'),
('Płochacz niemiecki, spaniel niemiecki', 'Deutscher Wachtelhund'),
('Retriever z Nowej Szkocji', 'Nova scotia duck tolling retriever'),
('Rodezyjski ridgeback', 'Rhodesian ridgeback'),
('Rosyjski toy', 'Russkij toj-tierjer'),
('Rottweiler', 'Rottweiler'),
('Samojed', 'Samojedskaja sobaka'),
('Sarplaninac', 'Jugoslovenski ovčarski pas šarplaninac'),
('Seter angielski', 'English setter'),
('Seter irlandzki czerwono-biały, irlandzki seter rudo-biały', 'Irish red and white setter'),
('Seter irlandzki', 'Irish red setter'),
('Seter szkocki (gordon), seter gordon, gordon seter', 'Gordon setter'),
('Spaniel Pont-Audemer', 'Épagneul de Pont-Audemer'),
('Spaniel francuski', 'Épagneul français'),
('Spaniel kontynentalny miniaturowy', 'Épagneul nain continental'),
('Spaniel pikardyjski', 'Épagneul picard'),
('Spaniel tybetański', 'Tibetan spaniel'),
('Springer spaniel angielski', 'English springer spaniel'),
('Springer spaniel walijski', 'Welsh springer spaniel'),
('Sznaucer miniaturowy, brodacz miniaturowy', 'Zwergschnauzer'),
('Sznaucer olbrzym, brodacz olbrzym', 'Riesenschnauzer'),
('Sznaucer średni, brodacz średni', 'Schnauzer'),
('Szorstkowłosy gończy bretoński', 'Griffon fauve de Bretagne'),
('Szorstkowłosy gończy gaskoński', 'Griffon bleu de Gascogne'),
('Szorstkowłosy gończy z Nivernais', 'Griffon nivernais'),
('Szpic fiński', 'Suomenpystykorva'),
('Szpic japoński', 'Nihon supittsu'),
('Szpic niemiecki', 'Deutsche Spitze'),
('Szpic nordycki', 'Norrbottenspets'),
('Szpic włoski', 'Volpino italiano'),
('Szwedzki elkhund', 'Jämthund'),
('Szwedzki lapphund', 'Svensk lapphund'),
('Szwedzki vallhund', 'Västgötaspets'),
('Śpiewający pies z Nowej Gwinei', 'New guinea singing dog'),
('Terier australijski', 'Australian terrier'),
('Terier brazylijski', 'Terrier brasileiro'),
('Terier czeski', 'Český teriér'),
('Terier irlandzki', 'Irish terrier'),
('Terier japoński', 'Nihon teria'),
('Terier szkocki', 'Scottish terrier, aberdeen terrier'),
('Terier tybetański', 'Tibetan terrier'),
('Terier walijski', 'Welsh terrier'),
('Tosa, tosa inu, mastif japoński', 'Tosa inu'),
('Westfalski gończy krótkonożny, gończak westfalski', 'Westfälische Dachsbracke'),
('Wilczak czechosłowacki', 'Československý vlčiák'),
('Wilczarz irlandzki', 'Irish wolfhound'),
('Wyżeł czeski szorstkowłosy', 'Český fousek'),
('Wyżeł duński', 'Gammel dansk honsehund'),
('Wyżeł fryzyjski', 'Stabyhoun'),
('Wyżeł gaskoński', 'Braque français, type gascogne'),
('Wyżeł hiszpański z Burgos, pointer hiszpański', 'Perdiguero de Burgos'),
('Wyżeł niemiecki długowłosy', 'Deutsch Langhaar'),
('Wyżeł niemiecki krótkowłosy', 'Deutsch Kurzhaar'),
('Wyżeł niemiecki ostrowłosy', 'Deutsch Stichelhaar'),
('Wyżeł niemiecki szorstkowłosy', 'Deutsch Drahthaar'),
('Wyżeł pirenejski', 'Braque français, type pyrénées'),
('Wyżeł portugalski, pointer portugalski', 'Perdigueiro portuguęs'),
('Wyżeł słowacki szorstkowłosy, słowacki pointer', 'Slovenský hrubosrstý stavač'),
('Wyżeł weimarski', 'Weimaraner'),
('Wyżeł węgierski krótkowłosy', 'Rövidszőrű magyar vizsla'),
('Wyżeł węgierski szorstkowłosy', 'Drótszőrű magyar vizsla'),
('Wyżeł włoski krótkowłosy', 'Bracco italiano'),
('Wyżeł włoski szorstkowłosy, włoski spinone', 'Spinone italiano');