('Owczarki i inne psy pasterskie (bez ON)','Asystent Dorota Gajowiak','Stażysta Jadwiga Sagan','wtorek'),
('Owczarki niemieckie','Dariusz Lorenc','','piątek'),
('Boksery','Izabela Oleś','Stażysta Sylwia Persyk-Waszkiewicz','piątek'),
('Sznaucery, pinczery','Anna Bielińska','','wtorek'),
('Molosy, szwajcarskie psy pasterskie','Asystent Alicja Mech','Izabela Zych, Ewa Wiśnios','wtorek'),
('Teriery','Sędzia międzynarodowy Andrzej Pławiński','','wtorek'),
('Jamniki','Dorota Rykaczewska','','piątek'),
('Szpice i psy w typie pierwotnym','Asystent Grażyna Kowalska-Jarosz','Beata Dziemianko, Grzegorz Wolski','wtorek, piątek'),
('Psy gończe i rasy pokrewne','Sędzia Międzynarodowy Andrzej Czesnowski','Monika Thomas-Czerepkow','piątek'),
('Wyżły','Sędzia krajowy Aleksandra Zukal','Asystent Anna Michalczyk, Stażysta Jadwiga Sagan, Ewa Wiśnios','wtorek, piątek'),
('Aportery, płochacze i psy dowodowe','Sędzia międzynarodowy Maciej Wytyk','','wtorek'),
('Psy ozdobne i do towarzystwa','Joanna Chruścicka','Adrian Alasiński, Izabela Oleś','piątek'),
('Charty','Aleksandra Zukal','','wtorek, piątek');
