('Wpisowe','opłata jednorazowa od członka przy wstąpieniu do ZKwP','60 zł'),
('Składka członkowska','członek, za 1 rok','70 zł'),
('Rejestracja psa/suki','opłata za rejestrację psa/suki','30 zł'),
('Metryka','dokument dla 1 szczenięcia','30 zł'),
('Karta miotu','dokument na 1 miot','25 zł'),
('Przegląd miotu','usługa na 1 miot','35 zł'),
('Karta krycia','dokument na 1 krycie','30 zł'),
('Rodowód krajowy','dokument dla 1 psa','50 zł'),
('Rodowód eksportowy','dokument dla 1 psa','100 zł'),
('Rodowód eksportowy (ekspres)','dokument dla 1 psa','300 zł'),
('Nostryfikacja','dokument dla 1 psa','50 zł'),
('Nostryfikacja (ekspres)','dokument dla 1 psa','150 zł'),
('Księga wstępna','dokument dla 1 psa','50 zł'),
('Przydomek hodowlany','każda zmiana','100 zł'),
('Wpis do FCI','','50 zł'),
('Tatuaż','1 szczenię','5 zł');